package vista;


/* 
this.btnLogIn = new JButton("Log In");
this.btnLogIn.setActionCommand("LogIn");


public void setControlador(ControladorLogin c){
		this.btnLogIn.addActionListener(c);
		this.btnRegistrarse.addActionListener(c);
	}


*/


import modelo.Contacto;
import controlador.Controlador;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.Font;
import modelo.Sistema;



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Usuario
 */

public class Vista extends javax.swing.JFrame {

    private static final long serialVersionUID = 1L;

	/**
     * Creates new form Vista
     */
    public Vista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tabbedPane = new javax.swing.JTabbedPane();
        panelChats = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaChats = new javax.swing.JList<>();
        jPanel3 = new javax.swing.JPanel();
        nombreChatSeleccionado = new javax.swing.JLabel();
        textoMensaje = new javax.swing.JTextField();
        bEnviar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        chat = new javax.swing.JTextArea();
        panelContactos = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        listaContactos = new javax.swing.JList<>();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        nickContactoAgregado = new javax.swing.JTextField();
        nickContactoAgregado.setFont(new Font("Tahoma", Font.PLAIN, 15));
        bAgregarContacto = new javax.swing.JButton();
        bAgregarContacto.setFont(new Font("Tahoma", Font.PLAIN, 13));
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        nicknameUsuario = new javax.swing.JLabel();
        puertoUsuario = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        tabbedPane.setBackground(new java.awt.Color(255, 255, 255));
        tabbedPane.setForeground(new java.awt.Color(245, 85, 132));
        tabbedPane.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        tabbedPane.setFont(new java.awt.Font("Meiryo", 0, 14)); // NOI18N

        panelChats.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Meiryo UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(245, 85, 132));
        jLabel1.setText("chats activos");

        listaChats.setFont(new java.awt.Font("Meiryo UI", 0, 14)); // NOI18N
        listaChats.setForeground(new java.awt.Color(245, 85, 132));
        listaChats.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listaChats.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        //listaChats.addMouseListener(new java.awt.event.MouseAdapter() {
        //    public void mouseClicked(java.awt.event.MouseEvent evt) {
        //        listaChatsMouseClicked(evt);
        //    }
        //});
        jScrollPane1.setViewportView(listaChats);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        nombreChatSeleccionado.setBackground(new java.awt.Color(255, 255, 255));
        nombreChatSeleccionado.setFont(new java.awt.Font("Meiryo UI", 0, 14)); // NOI18N
        nombreChatSeleccionado.setForeground(new java.awt.Color(245, 85, 132));

        textoMensaje.setFont(new java.awt.Font("Meiryo UI", 0, 12)); // NOI18N
        textoMensaje.setForeground(new java.awt.Color(245, 85, 132));
        textoMensaje.setText("ingrese su texto aqui ...");
        textoMensaje.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textoMensajeMouseClicked(evt);
            }
        });
        textoMensaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoMensajeActionPerformed(evt);
            }
        });

        bEnviar.setFont(new java.awt.Font("Meiryo UI", 0, 12)); // NOI18N
        bEnviar.setForeground(new java.awt.Color(245, 85, 132));
        bEnviar.setText("enviar");
        bEnviar.setActionCommand("Enviar");
        //bEnviar.addActionListener(new java.awt.event.ActionListener() {
        //    public void actionPerformed(java.awt.event.ActionEvent evt) {
        //        bEnviarActionPerformed(evt);
        //    }
        //});

        chat.setColumns(20);
        chat.setFont(new java.awt.Font("Meiryo UI", 0, 12)); // NOI18N
        chat.setForeground(new java.awt.Color(245, 85, 132));
        chat.setRows(5);
        jScrollPane2.setViewportView(chat);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3Layout.setHorizontalGroup(
        	jPanel3Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel3Layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(jPanel3Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanel3Layout.createSequentialGroup()
        					.addComponent(textoMensaje, GroupLayout.PREFERRED_SIZE, 369, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(bEnviar, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        				.addComponent(jScrollPane2, GroupLayout.PREFERRED_SIZE, 455, GroupLayout.PREFERRED_SIZE)
        				.addComponent(nombreChatSeleccionado, GroupLayout.PREFERRED_SIZE, 138, GroupLayout.PREFERRED_SIZE))
        			.addContainerGap(7, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
        	jPanel3Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel3Layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(nombreChatSeleccionado, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(jScrollPane2, GroupLayout.PREFERRED_SIZE, 390, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(jPanel3Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(textoMensaje, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(bEnviar))
        			.addContainerGap())
        );
        jPanel3.setLayout(jPanel3Layout);

        javax.swing.GroupLayout panelChatsLayout = new javax.swing.GroupLayout(panelChats);
        panelChatsLayout.setHorizontalGroup(
        	panelChatsLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(panelChatsLayout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(jPanel3, GroupLayout.PREFERRED_SIZE, 472, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(185, Short.MAX_VALUE))
        );
        panelChatsLayout.setVerticalGroup(
        	panelChatsLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(Alignment.TRAILING, panelChatsLayout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(panelChatsLayout.createParallelGroup(Alignment.TRAILING)
        				.addComponent(jPanel3, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        				.addComponent(jPanel2, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 487, Short.MAX_VALUE))
        			.addContainerGap())
        );
        panelChats.setLayout(panelChatsLayout);

        tabbedPane.addTab("chats", panelChats);

        panelContactos.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Meiryo UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(245, 85, 132));
        jLabel4.setText("lista de contactos");

        listaContactos.setFont(new java.awt.Font("Meiryo UI", 0, 14)); // NOI18N
        listaContactos.setForeground(new java.awt.Color(245, 85, 132));
        listaContactos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listaContactos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        //listaContactos.addMouseListener(new java.awt.event.MouseAdapter() {
        //    public void mouseClicked(java.awt.event.MouseEvent evt) {
        //        listaContactosMouseClicked(evt);
        //    }
        //});
        jScrollPane3.setViewportView(listaContactos);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new Font("Dialog", Font.PLAIN, 19)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(245, 85, 132));
        jLabel5.setText("Agregar contacto");

        nickContactoAgregado.setForeground(new java.awt.Color(245, 85, 132));
        nickContactoAgregado.setText("nickname");
        nickContactoAgregado.setCaretColor(new java.awt.Color(255, 204, 204));
        nickContactoAgregado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nickContactoAgregadoMouseClicked(evt);
            }
        });
        nickContactoAgregado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nickContactoAgregadoActionPerformed(evt);
            }
        });

        bAgregarContacto.setForeground(new java.awt.Color(245, 85, 132));
        bAgregarContacto.setText("agregar");
        bAgregarContacto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bAgregarContactoMouseClicked(evt);
            }
        });
        bAgregarContacto.setActionCommand("AgregarContacto");
        //bAgregarContacto.addActionListener(new java.awt.event.ActionListener() {
        //    public void actionPerformed(java.awt.event.ActionEvent evt) {
        //        bAgregarContactoActionPerformed(evt);
        //    }
        //});

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5Layout.setHorizontalGroup(
        	jPanel5Layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(jPanel5Layout.createSequentialGroup()
        			.addContainerGap(108, Short.MAX_VALUE)
        			.addGroup(jPanel5Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanel5Layout.createSequentialGroup()
        					.addComponent(bAgregarContacto, GroupLayout.PREFERRED_SIZE, 82, GroupLayout.PREFERRED_SIZE)
        					.addContainerGap())
        				.addGroup(Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
        					.addGroup(jPanel5Layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(nickContactoAgregado, 269, 269, 269)
        						.addGroup(jPanel5Layout.createSequentialGroup()
        							.addComponent(jLabel5)
        							.addGap(172)))
        					.addGap(92))))
        );
        jPanel5Layout.setVerticalGroup(
        	jPanel5Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel5Layout.createSequentialGroup()
        			.addGap(58)
        			.addComponent(jLabel5)
        			.addGap(29)
        			.addComponent(nickContactoAgregado, GroupLayout.PREFERRED_SIZE, 29, GroupLayout.PREFERRED_SIZE)
        			.addGap(18)
        			.addComponent(bAgregarContacto)
        			.addContainerGap(95, Short.MAX_VALUE))
        );
        jPanel5.setLayout(jPanel5Layout);

        javax.swing.GroupLayout panelContactosLayout = new javax.swing.GroupLayout(panelContactos);
        panelContactosLayout.setHorizontalGroup(
        	panelContactosLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(panelContactosLayout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jPanel4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(jPanel5, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(82, Short.MAX_VALUE))
        );
        panelContactosLayout.setVerticalGroup(
        	panelContactosLayout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(panelContactosLayout.createSequentialGroup()
        			.addGroup(panelContactosLayout.createParallelGroup(Alignment.LEADING)
        				.addGroup(panelContactosLayout.createSequentialGroup()
        					.addContainerGap()
        					.addComponent(jPanel4, GroupLayout.DEFAULT_SIZE, 487, Short.MAX_VALUE))
        				.addGroup(panelContactosLayout.createSequentialGroup()
        					.addGap(119)
        					.addComponent(jPanel5, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
        			.addContainerGap())
        );
        panelContactos.setLayout(panelContactosLayout);

        tabbedPane.addTab("contactos", panelContactos);

        jPanel6.setBackground(new java.awt.Color(255, 204, 204));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel7.setBackground(new java.awt.Color(255, 204, 204));

        nicknameUsuario.setFont(new java.awt.Font("Meiryo UI", 1, 18)); // NOI18N
        nicknameUsuario.setForeground(new java.awt.Color(000));
        nicknameUsuario.setText("usuario");

        puertoUsuario.setBackground(new java.awt.Color(255, 204, 204));
        puertoUsuario.setFont(new java.awt.Font("Meiryo UI", 0, 12)); // NOI18N
        puertoUsuario.setForeground(new java.awt.Color(0, 0, 0));
        puertoUsuario.setText("puerto");
        puertoUsuario.setToolTipText("");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nicknameUsuario)
                    .addComponent(puertoUsuario))
                .addContainerGap(165, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(nicknameUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(puertoUsuario)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1Layout.setHorizontalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addComponent(jPanel6, GroupLayout.PREFERRED_SIZE, 92, GroupLayout.PREFERRED_SIZE)
        					.addGap(18)
        					.addComponent(jPanel7, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        				.addComponent(tabbedPane, GroupLayout.PREFERRED_SIZE, 799, GroupLayout.PREFERRED_SIZE))
        			.addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(jPanel6, 0, 0, Short.MAX_VALUE)
        				.addComponent(jPanel7, GroupLayout.PREFERRED_SIZE, 76, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(tabbedPane, GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE)
        			.addGap(36))
        );
        jPanel1.setLayout(jPanel1Layout);
        GroupLayout groupLayout = new GroupLayout(getContentPane());
        groupLayout.setHorizontalGroup(
        	groupLayout.createParallelGroup(Alignment.LEADING)
        		.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        );
        groupLayout.setVerticalGroup(
        	groupLayout.createParallelGroup(Alignment.LEADING)
        		.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, 636, GroupLayout.PREFERRED_SIZE)
        );
        getContentPane().setLayout(groupLayout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nickContactoAgregadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nickContactoAgregadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nickContactoAgregadoActionPerformed

    private void bEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEnviarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bEnviarActionPerformed

    private void bAgregarContactoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bAgregarContactoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_bAgregarContactoMouseClicked

    private void bAgregarContactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAgregarContactoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bAgregarContactoActionPerformed

    private void nickContactoAgregadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nickContactoAgregadoMouseClicked
        nickContactoAgregado.setText("");
    }//GEN-LAST:event_nickContactoAgregadoMouseClicked

    private void textoMensajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoMensajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoMensajeActionPerformed

    private void textoMensajeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textoMensajeMouseClicked
        // TODO add your handling code here:
        textoMensaje.setText("");
    }//GEN-LAST:event_textoMensajeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista().setVisible(true);
            }
        });

  
    }

    public void setNickUsuario(String nickUsuario){
        this.nicknameUsuario.setText(nickUsuario);
    }

    public void setPuertoUsuario(int puertoUsuario){
        String aux = Integer.toString(puertoUsuario);
        this.puertoUsuario.setText(aux);
    }

    public String getNicknameUsuario(){
        return this.nicknameUsuario.getText();
    }

    public int getPuertoUsuario(){
        return Integer.parseInt(this.puertoUsuario.getText());
    }
    
    public String getNickContactoAgregado() {
        String aux = this.nickContactoAgregado.getText();
        if (!aux.equals(""))
                return aux;
        JOptionPane.showMessageDialog(null,"Debe introducir nombre de usuario");
        return null;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAgregarContacto;
    private javax.swing.JButton bEnviar;
    private javax.swing.JTextArea chat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> listaChats;
    private javax.swing.JList<String> listaContactos;
    private javax.swing.JTextField nickContactoAgregado;
    private javax.swing.JLabel nicknameUsuario;
    private javax.swing.JLabel nombreChatSeleccionado;
    private javax.swing.JPanel panelChats;
    private javax.swing.JPanel panelContactos;
    private javax.swing.JLabel puertoUsuario;
    private javax.swing.JTabbedPane tabbedPane;
    private javax.swing.JTextField textoMensaje;
    // End of variables declaration//GEN-END:variables
    
    public void setControlador(Controlador c){
		this.bEnviar.addActionListener(c);
		this.bAgregarContacto.addActionListener(c);
        listaContactos.setModel(Sistema.getInstance().getNicksContactos());
        listaChats.setModel(Sistema.getInstance().getNicksChats()); 
        
        listaContactos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt){
                c.listaContactosMouseClicked(evt);
            }
        });
        listaChats.addMouseListener(new java.awt.event.MouseAdapter(){
            public void mouseClicked(java.awt.event.MouseEvent evt){
                c.listaChatsMouseClicked(evt);
            }
        });
    
    }
    public void limpiaChat(){
        this.chat.setText("");
    }
    
     public void cargaChat(ArrayList<String> mensajes) {
        for (String mensaje : mensajes){
            String[] mensajeFormateado = mensaje.split("#", 3);
            String hora = mensajeFormateado[1].substring(11,16);
            this.chat.append(mensajeFormateado[0] + " ["+ hora +"]: " +mensajeFormateado[2] + "\n");
        }
    }

	
    
    private void textoMensajeKeyReleased(java.awt.event.KeyEvent evt) {
        if (textoMensaje.getText().length() != 0) {
            bEnviar.setEnabled(true);
        } else {
            bEnviar.setEnabled(false);
        }
    }
    public String getMensaje(){
    try{
        String aux = this.textoMensaje.getText();
        if (aux != null && !aux.equals(""))
                return aux;
    } catch (NullPointerException e){
    }
    return null;
    }
    
    public void setNickChatSeleccionado(String nickname) {
        this.nombreChatSeleccionado.setText(nickname);
    }


    public void cambiarAVentanaChat() {
        this.tabbedPane.setSelectedIndex(0); // Cambia al tab donde están los chats
    }

    public String getListaContactosSeleccionado(){
        return listaContactos.getSelectedValue();
    }

    public String getListaChatsSeleccionado(){
        return listaChats.getSelectedValue();
    }

    public String getTextoMensaje(){
        return textoMensaje.getText();
    }

    public void setTextoMensaje(String string){
        textoMensaje.setText(string);
    }

    public String getNicknameChatSeleccionado(){
        return this.nombreChatSeleccionado.getText();
    }

    public void muestraVentanaEmergente(String mensaje){
        JOptionPane.showMessageDialog(this, mensaje);
    }

}

